switch("app", "console")
switch("d", "noSignalHandler")
switch("exceptions", "goto")
switch("mm", "orc")
switch("d", "noSignalHandler")
switch("d", "useMalloc")
switch("nimcache", "nimcache")
switch("opt", "size")
switch("panics", "on")
switch("threads", "off")
switch("w", "on")

switch("d", "danger")
switch("lineTrace", "off")
switch("stackTrace", "off")
switch("checks", "off")

switch("passC", "-flto")
switch("passL", "-flto")
